### ISSUE TITLE
Creazione db

### ISSUE THREAD

**Issue by MatteoMiotello** [MatteoMiotello/ProgettoTecWeb#1]
# Implementazione

Deve essere creato un database che possa soddisfare queste linee guida:
- Tabella che contenga tutti gli articoli del giornale
   -  `Titolo articolo`
   -  `Testo articolo`
   - `Percorso dell'immagine dell'articolo`
   - `Descrizione dell'immagine`
   - `id della categoria`
   - `id dell'utente`
   - `rating`

- Tabella che contenga tutte le categorie
   - `Nome categoria`
   - `descrizione`

- Tabella che contenga i commenti 
   - `Titolo del commento`
   - `Testo del commento`
   - `id dell'utente`

- Tabella degli utenti
   - `Nome`
   - `Cognome`
   - `username`
   - `livello autorizzazione`
   - `password`

**Comment by alketaz** [comment]
### Struttura DB corretta

**UTENTE** (_ID_, Nome, Cognome, email, password, permesso, immagine*)
**ARTICOLO** (_ID_, titolo, testo, autore, data_pubb*, upvotes, downvotes, immagine*)
autore->UTENTE.ID
**CATEGORIA** (_Nome_, descrizione)
**COMMENTO** (_ID_Art_, _ID_Comm_, autore, data_pubb, upvotes, downvotes)
ID_Art -> ARTICOLO.ID
autore -> UTENTE.ID
**CAT_ART** (_Nome_Cat_, ID_Art)
Nome_Cat->CATEGORIA.Nome
ID_Art -> ARTICOLO.ID

Nota: * = può essere null

**Comment by MatteoMiotello** [comment]
@alketaz Per quanto riguarda la tabella "ARTICOLO" si dovrebbe aggiungere il campo `image_description` per poi poter aggiungere l'alt come attributo dell'immagine
